name: Unit Tests, Beta Toolchain

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests-beta:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Beta Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Install the latest beta Rust toolchain
        uses: dtolnay/rust-toolchain@beta
      - name: Run tests
        run: cargo install siz && siz -c .
